# Generated by Django 5.0.4 on 2024-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_drivinglicence_drivinglicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
